import { Link } from "react-router-dom";
import { ArrowLeft, BedDouble, Check, ChevronDown, Heart, List, Map, MapPin, Search, ShieldCheck, SlidersHorizontal, Star, X } from "lucide-react";
import { useState } from "react";

const results = [
  { name: "Greenfield Residence", area: "Yaba, Lagos", school: "University of Lagos", price: "₦450,000", rating: "4.9", beds: "12 spaces left", image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=900&q=85", verified: true },
  { name: "Campus View House", area: "Gwagwalada, Abuja", school: "University of Abuja", price: "₦380,000", rating: "4.8", beds: "5 spaces left", image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=85", verified: true },
  { name: "The Study Grove", area: "Ile-Ife, Osun", school: "Obafemi Awolowo University", price: "₦290,000", rating: "4.7", beds: "18 spaces left", image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=85", verified: true },
  { name: "The Junction", area: "Akoka, Lagos", school: "University of Lagos", price: "₦520,000", rating: "4.8", beds: "3 spaces left", image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=85", verified: false },
];

export default function FindHostel() {
  const [mapView, setMapView] = useState(false);
  const [saved, setSaved] = useState<string[]>([]);
  const [filters, setFilters] = useState(false);
  const toggleSave = (name: string) => setSaved(s => s.includes(name) ? s.filter(x => x !== name) : [...s, name]);
  return <div className="min-h-screen bg-[#faf9f7] text-[#171717]">
    <header className="sticky top-0 z-40 border-b border-black/10 bg-[#faf9f7]/95 backdrop-blur-md"><div className="mx-auto flex h-[74px] max-w-[1240px] items-center justify-between px-5 lg:px-8"><Link to="/" className="font-display text-[25px] font-extrabold tracking-[-0.08em]">arc<span className="text-[#f5b544]">()</span></Link><nav className="hidden items-center gap-7 text-[13px] font-medium lg:flex"><Link to="/" className="transition hover:text-[#a36500]">Home</Link><span className="font-bold text-[#a36500]">Find hostels</span><span>Universities</span><span>How it works</span></nav><div className="flex items-center gap-3"><button className="hidden px-3 text-[13px] font-semibold sm:block">Log in</button><button className="rounded-full bg-black px-4 py-2 text-[13px] font-semibold text-white">List your hostel</button></div></div></header>
    <main className="mx-auto max-w-[1240px] px-5 py-12 lg:px-8 lg:py-16"><div className="mb-8"><Link to="/" className="mb-6 inline-flex items-center text-xs font-bold text-black/50 hover:text-black"><ArrowLeft className="mr-2 h-4 w-4" /> Back to home</Link><h1 className="font-display text-[clamp(2.6rem,5vw,4.8rem)] font-extrabold leading-none tracking-[-.07em]">Find your next <span className="text-[#e5a32d]">home.</span></h1><p className="mt-4 max-w-[480px] text-sm leading-6 text-black/55">Search trusted accommodation around your university and compare the details that matter most.</p></div>
      <div className="rounded-2xl border border-black/10 bg-white p-3 shadow-sm"><div className="grid gap-2 md:grid-cols-[1.3fr_1fr_1fr_1fr_1fr_auto]"><label className="search-field"><MapPin /><span><small>University</small><input defaultValue="University of Lagos" /></span></label><label className="search-field"><MapPin /><span><small>Location</small><input placeholder="City or area" /></span></label><label className="search-field"><span><small>Move-in</small><input placeholder="Any date" /></span></label><label className="search-field"><BedDouble /><span><small>Room type</small><input placeholder="Any room" /></span></label><label className="search-field"><span><small>Budget</small><input placeholder="Any budget" /></span></label><button className="flex items-center justify-center rounded-xl bg-[#f5b544] px-5 py-3 text-sm font-extrabold transition hover:bg-black hover:text-white"><Search className="mr-2 h-4 w-4" /> Search</button></div></div>
      <div className="mt-10 flex flex-col gap-4 border-b border-black/10 pb-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-display text-xl font-extrabold">128 hostels found</p><p className="mt-1 text-xs text-black/45">Near University of Lagos · Updated today</p></div><div className="flex gap-2"><button onClick={() => setFilters(!filters)} className="flex items-center rounded-full border border-black/15 px-4 py-2 text-xs font-bold lg:hidden"><SlidersHorizontal className="mr-2 h-4 w-4" /> Filters</button><button className="flex items-center rounded-full border border-black/15 px-4 py-2 text-xs font-bold">Sort: Recommended <ChevronDown className="ml-2 h-4 w-4" /></button><div className="hidden overflow-hidden rounded-full border border-black/15 sm:flex"><button onClick={() => setMapView(false)} className={`p-2 ${!mapView ? "bg-black text-white" : ""}`} aria-label="List view"><List className="h-4 w-4" /></button><button onClick={() => setMapView(true)} className={`p-2 ${mapView ? "bg-black text-white" : ""}`} aria-label="Map view"><Map className="h-4 w-4" /></button></div></div></div>
      <div className="mt-7 grid gap-8 lg:grid-cols-[220px_1fr]">{(filters || true) && <aside className={`${filters ? "block" : "hidden lg:block"} rounded-2xl border border-black/10 bg-white p-5 lg:h-fit`}><div className="mb-6 flex items-center justify-between"><h2 className="font-display font-extrabold">Filters</h2><button className="text-xs font-semibold text-[#a36500]">Clear all</button>{filters && <button onClick={() => setFilters(false)} className="lg:hidden"><X className="h-4 w-4" /></button>}</div>{[["Price range", "₦0 — ₦800k"],["Room type", "Any room type"],["Distance", "Within 5 km"],["Amenities", "All amenities"],["Gender", "Mixed"],["Availability", "Available now"]].map(([label,value]) => <div className="border-t border-black/10 py-4" key={label}><div className="flex items-center justify-between text-sm font-semibold"><span>{label}</span><ChevronDown className="h-4 w-4 text-black/40" /></div><p className="mt-2 text-xs text-black/45">{value}</p>{label === "Price range" && <div className="mt-3 h-1 rounded-full bg-black/10"><div className="ml-[5%] h-full w-[65%] rounded-full bg-[#f5b544]" /></div>}</div>)}</aside>}
        <div>{mapView ? <div className="relative flex min-h-[600px] items-center justify-center overflow-hidden rounded-2xl bg-[#e8e2d7]" style={{backgroundImage: "radial-gradient(#b9b1a4 1px, transparent 1px)", backgroundSize: "22px 22px"}}><div className="absolute left-[25%] top-[26%] rounded-full bg-black p-3 text-white shadow-xl"><MapPin /></div><div className="absolute left-[58%] top-[40%] rounded-full bg-[#f5b544] p-3 text-black shadow-xl"><MapPin /></div><div className="absolute left-[42%] top-[67%] rounded-full bg-black p-3 text-white shadow-xl"><MapPin /></div><div className="absolute bottom-5 left-5 rounded-xl bg-white p-4 text-sm font-bold shadow-lg">Showing hostels near University of Lagos</div></div> : <div className="grid gap-5 md:grid-cols-2">{results.map(h => <Link to="/hostels/greenfield-residence" className="group overflow-hidden rounded-2xl border border-black/10 bg-white transition hover:-translate-y-1 hover:shadow-xl" key={h.name}><div className="relative h-52 overflow-hidden"><img src={h.image} alt={h.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><div className="absolute inset-x-0 top-0 flex justify-between p-4">{h.verified ? <span className="rounded-full bg-white px-2.5 py-1.5 text-[10px] font-bold"><ShieldCheck className="mr-1 inline h-3 w-3 text-[#1f9d55]" /> Verified</span> : <span /> }<button onClick={e => {e.preventDefault(); toggleSave(h.name)}} className="rounded-full bg-white/90 p-2" aria-label="Save hostel"><Heart className={`h-4 w-4 ${saved.includes(h.name) ? "fill-[#e5a32d] text-[#e5a32d]" : ""}`} /></button></div></div><div className="p-5"><div className="flex justify-between gap-3"><div><h3 className="font-display text-xl font-extrabold">{h.name}</h3><p className="mt-1 text-xs text-black/50"><MapPin className="mr-1 inline h-3 w-3" />{h.area} · 2.4km away</p></div><span className="flex h-fit items-center gap-1 text-sm font-bold"><Star className="h-4 w-4 fill-[#f5b544] text-[#f5b544]" />{h.rating}</span></div><p className="mt-3 text-xs text-black/45">{h.school}</p><div className="mt-5 flex items-end justify-between border-t border-black/10 pt-4"><div><p className="text-[11px] text-black/45">Starting from</p><p className="font-display text-lg font-extrabold">{h.price} <span className="font-sans text-xs font-medium text-black/45">/ session</span></p></div><span className="text-xs font-bold text-[#a36500]">{h.beds}</span></div></div></Link>)}</div>}</div></div>
    </main>
  </div>;
}
