import { ArrowLeft, BedDouble, ChevronDown, Heart, List, Map, MapPin, Search, ShieldCheck, SlidersHorizontal, Star, X } from "lucide-react";
import { Link } from "react-router-dom";
import { useMemo, useState } from "react";

const hostels = [
  { id: "greenfield-residence", name: "Greenfield Residence", area: "Yaba, Lagos", school: "University of Lagos", price: 450000, rating: 4.9, beds: "12 spaces left", image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=900&q=85", verified: true, room: "Single", distance: 2.4 },
  { id: "campus-view-house", name: "Campus View House", area: "Gwagwalada, Abuja", school: "University of Abuja", price: 380000, rating: 4.8, beds: "5 spaces left", image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=85", verified: true, room: "Shared", distance: 1.8 },
  { id: "study-grove", name: "The Study Grove", area: "Ile-Ife, Osun", school: "Obafemi Awolowo University", price: 290000, rating: 4.7, beds: "18 spaces left", image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=85", verified: true, room: "Studio", distance: 3.1 },
  { id: "the-junction", name: "The Junction", area: "Akoka, Lagos", school: "University of Lagos", price: 520000, rating: 4.8, beds: "3 spaces left", image: "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=900&q=85", verified: false, room: "Single", distance: 4.2 },
];

type Filters = { room: string; distance: string; availability: string; verified: boolean };
const defaultFilters: Filters = { room: "Any room type", distance: "Within 5 km", availability: "Available now", verified: false };

export default function FindHostel() {
  const [mapView, setMapView] = useState(false);
  const [filtersOpen, setFiltersOpen] = useState(false);
  const [sortOpen, setSortOpen] = useState(false);
  const [sort, setSort] = useState("Recommended");
  const [university, setUniversity] = useState("University of Lagos");
  const [location, setLocation] = useState("");
  const [budget, setBudget] = useState("");
  const [filters, setFilters] = useState<Filters>(defaultFilters);
  const [saved, setSaved] = useState<string[]>([]);

  const filtered = useMemo(() => {
    const list = hostels.filter(hostel => {
      const matchesLocation = !location || hostel.area.toLowerCase().includes(location.toLowerCase());
      const matchesSchool = !university || hostel.school.toLowerCase().includes(university.toLowerCase()) || university === "University of Lagos";
      const matchesRoom = filters.room === "Any room type" || hostel.room === filters.room;
      const matchesDistance = filters.distance === "Within 5 km" ? hostel.distance <= 5 : hostel.distance <= 2;
      const matchesBudget = !budget || hostel.price <= Number(budget);
      return matchesLocation && matchesSchool && matchesRoom && matchesDistance && matchesBudget && (!filters.verified || hostel.verified);
    });
    if (sort === "Price: low to high") return [...list].sort((a, b) => a.price - b.price);
    if (sort === "Rating") return [...list].sort((a, b) => b.rating - a.rating);
    return list;
  }, [budget, filters, location, sort, university]);

  return <div className="min-h-screen bg-[#faf9f7] text-[#171717]">
    <Header />
    <main className="mx-auto max-w-[1240px] px-5 py-12 lg:px-8 lg:py-16">
      <Link to="/" className="mb-6 inline-flex items-center text-xs font-bold text-black/50 hover:text-black"><ArrowLeft className="mr-2 h-4 w-4" /> Back to home</Link>
      <h1 className="font-display text-[clamp(2.6rem,5vw,4.8rem)] font-extrabold leading-none tracking-[-.07em]">Find your next <span className="text-[#e5a32d]">home.</span></h1>
      <p className="mt-4 max-w-[480px] text-sm leading-6 text-black/55">Search trusted accommodation around your university and compare the details that matter most.</p>
      <form onSubmit={event => event.preventDefault()} className="mt-8 rounded-2xl border border-black/10 bg-white p-3 shadow-sm"><div className="grid gap-2 md:grid-cols-[1.3fr_1fr_1fr_1fr_1fr_auto]"><Field label="University"><input value={university} onChange={event => setUniversity(event.target.value)} placeholder="Where do you study?" /></Field><Field label="Location" icon={<MapPin />}><input value={location} onChange={event => setLocation(event.target.value)} placeholder="City or area" /></Field><Field label="Move-in"><input type="date" /></Field><Field label="Room type" icon={<BedDouble />}><select value={filters.room} onChange={event => setFilters({ ...filters, room: event.target.value })}><option>Any room type</option><option>Single</option><option>Shared</option><option>Studio</option></select></Field><Field label="Max budget"><input value={budget} onChange={event => setBudget(event.target.value.replace(/\D/g, ""))} placeholder="₦800,000" /></Field><button className="flex items-center justify-center rounded-xl bg-[#f5b544] px-5 py-3 text-sm font-extrabold hover:bg-black hover:text-white"><Search className="mr-2 h-4 w-4" /> Search</button></div></form>
      <div className="mt-10 flex flex-col gap-4 border-b border-black/10 pb-5 sm:flex-row sm:items-center sm:justify-between"><div><p className="font-display text-xl font-extrabold">{filtered.length} hostels found</p><p className="mt-1 text-xs text-black/45">Near {university || "your university"} · Updated today</p></div><div className="flex gap-2"><button onClick={() => setFiltersOpen(!filtersOpen)} className="flex items-center rounded-full border border-black/15 px-4 py-2 text-xs font-bold lg:hidden"><SlidersHorizontal className="mr-2 h-4 w-4" /> Filters</button><div className="relative"><button onClick={() => setSortOpen(!sortOpen)} className="flex items-center rounded-full border border-black/15 px-4 py-2 text-xs font-bold">Sort: {sort}<ChevronDown className="ml-2 h-4 w-4" /></button>{sortOpen && <div className="absolute right-0 top-11 z-20 w-44 rounded-xl border border-black/10 bg-white p-1 shadow-xl">{["Recommended", "Price: low to high", "Rating"].map(option => <button key={option} onClick={() => { setSort(option); setSortOpen(false); }} className="block w-full rounded-lg px-3 py-2 text-left text-xs font-semibold hover:bg-[#f7f6f3]">{option}</button>)}</div>}</div><div className="hidden overflow-hidden rounded-full border border-black/15 sm:flex"><button onClick={() => setMapView(false)} className={`p-2 ${!mapView ? "bg-black text-white" : ""}`}><List className="h-4 w-4" /></button><button onClick={() => setMapView(true)} className={`p-2 ${mapView ? "bg-black text-white" : ""}`}><Map className="h-4 w-4" /></button></div></div></div>
      <div className="mt-7 grid gap-8 lg:grid-cols-[220px_1fr]"><FilterPanel open={filtersOpen} filters={filters} setFilters={setFilters} close={() => setFiltersOpen(false)} /><div>{mapView ? <MapView count={filtered.length} /> : filtered.length ? <div className="grid gap-5 md:grid-cols-2">{filtered.map(hostel => <HostelCard key={hostel.id} hostel={hostel} saved={saved.includes(hostel.name)} onSave={() => setSaved(current => current.includes(hostel.name) ? current.filter(name => name !== hostel.name) : [...current, hostel.name])} />)}</div> : <Empty onClear={() => { setFilters(defaultFilters); setBudget(""); setLocation(""); }} />}</div></div>
    </main>
  </div>;
}
function Header() { return <header className="sticky top-0 z-40 border-b border-black/10 bg-[#faf9f7]/95 backdrop-blur-md"><div className="mx-auto flex h-[74px] max-w-[1240px] items-center justify-between px-5 lg:px-8"><Link to="/" className="font-display text-[25px] font-extrabold tracking-[-.08em]">arc<span className="text-[#f5b544]">()</span></Link><nav className="hidden items-center gap-7 text-[13px] font-medium lg:flex"><Link to="/" className="hover:text-[#a36500]">Home</Link><span className="font-bold text-[#a36500]">Find hostels</span><Link to="/universities" className="hover:text-[#a36500]">Universities</Link><Link to="/how-it-works" className="hover:text-[#a36500]">How it works</Link></nav><div className="flex items-center gap-3"><Link to="/login" className="hidden px-3 text-[13px] font-semibold sm:block">Log in</Link><Link to="/owner/dashboard" className="rounded-full bg-black px-4 py-2 text-[13px] font-semibold text-white">List your hostel</Link></div></div></header>; }
function Field({ label, icon, children }: { label: string; icon?: React.ReactNode; children: React.ReactNode }) { return <label className="search-field">{icon ?? <span className="w-4" />}<span><small>{label}</small>{children}</span></label>; }
function FilterPanel({ open, filters, setFilters, close }: { open: boolean; filters: Filters; setFilters: (filters: Filters) => void; close: () => void }) { return <aside className={`${open ? "block" : "hidden lg:block"} rounded-2xl border border-black/10 bg-white p-5 lg:h-fit`}><div className="mb-5 flex items-center justify-between"><h2 className="font-display font-extrabold">Filters</h2><div className="flex items-center gap-3"><button onClick={() => setFilters(defaultFilters)} className="text-xs font-semibold text-[#a36500]">Clear all</button>{open && <button onClick={close} className="lg:hidden"><X className="h-4 w-4" /></button>}</div></div><FilterSelect label="Room type" value={filters.room} options={["Any room type", "Single", "Shared", "Studio"]} onChange={value => setFilters({ ...filters, room: value })} /><FilterSelect label="Distance" value={filters.distance} options={["Within 5 km", "Within 2 km"]} onChange={value => setFilters({ ...filters, distance: value })} /><FilterSelect label="Availability" value={filters.availability} options={["Available now", "Any availability"]} onChange={value => setFilters({ ...filters, availability: value })} /><label className="border-t border-black/10 py-4 flex items-center gap-3 text-sm font-semibold"><input type="checkbox" checked={filters.verified} onChange={event => setFilters({ ...filters, verified: event.target.checked })} className="h-4 w-4 accent-[#f5b544]" /> Verified only</label></aside>; }
function FilterSelect({ label, value, options, onChange }: { label: string; value: string; options: string[]; onChange: (value: string) => void }) { const [expanded, setExpanded] = useState(false); return <div className="border-t border-black/10 py-4"><button onClick={() => setExpanded(!expanded)} className="flex w-full items-center justify-between text-sm font-semibold"><span>{label}</span><ChevronDown className={`h-4 w-4 text-black/40 ${expanded ? "rotate-180" : ""}`} /></button><p className="mt-2 text-xs text-black/45">{value}</p>{expanded && <div className="mt-2 space-y-1">{options.map(option => <button key={option} onClick={() => { onChange(option); setExpanded(false); }} className={`block w-full rounded-lg px-2 py-2 text-left text-xs ${value === option ? "bg-[#fff4d6] font-bold" : "hover:bg-[#f7f6f3]"}`}>{option}</button>)}</div>}</div>; }
function HostelCard({ hostel, saved, onSave }: { hostel: typeof hostels[number]; saved: boolean; onSave: () => void }) { return <Link to={`/hostels/${hostel.id}`} className="group overflow-hidden rounded-2xl border border-black/10 bg-white transition hover:-translate-y-1 hover:shadow-xl"><div className="relative h-52 overflow-hidden"><img src={hostel.image} alt={hostel.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-x-0 top-0 flex justify-between p-4">{hostel.verified ? <span className="rounded-full bg-white px-2.5 py-1.5 text-[10px] font-bold"><ShieldCheck className="mr-1 inline h-3 w-3 text-[#1f9d55]" /> Verified</span> : <span /> }<button onClick={event => { event.preventDefault(); onSave(); }} className="rounded-full bg-white/90 p-2"><Heart className={`h-4 w-4 ${saved ? "fill-[#e5a32d] text-[#e5a32d]" : ""}`} /></button></div></div><div className="p-5"><div className="flex justify-between gap-3"><div><h3 className="font-display text-xl font-extrabold">{hostel.name}</h3><p className="mt-1 text-xs text-black/50"><MapPin className="mr-1 inline h-3 w-3" />{hostel.area} · {hostel.distance}km away</p></div><span className="flex h-fit items-center gap-1 text-sm font-bold"><Star className="h-4 w-4 fill-[#f5b544] text-[#f5b544]" />{hostel.rating}</span></div><p className="mt-3 text-xs text-black/45">{hostel.school}</p><div className="mt-5 flex items-end justify-between border-t border-black/10 pt-4"><p className="font-display text-lg font-extrabold">₦{hostel.price.toLocaleString()} <span className="font-sans text-xs font-medium text-black/45">/ session</span></p><span className="text-xs font-bold text-[#a36500]">{hostel.beds}</span></div></div></Link>; }
function MapView({ count }: { count: number }) { return <div className="relative flex min-h-[600px] items-center justify-center overflow-hidden rounded-2xl bg-[#e8e2d7]" style={{ backgroundImage: "radial-gradient(#b9b1a4 1px, transparent 1px)", backgroundSize: "22px 22px" }}><MapPin className="absolute left-[25%] top-[26%] rounded-full bg-black p-3 text-white shadow-xl" /><MapPin className="absolute left-[58%] top-[40%] rounded-full bg-[#f5b544] p-3 text-black shadow-xl" /><MapPin className="absolute left-[42%] top-[67%] rounded-full bg-black p-3 text-white shadow-xl" /><div className="absolute bottom-5 left-5 rounded-xl bg-white p-4 text-sm font-bold shadow-lg">Showing {count} available hostels</div></div>; }
function Empty({ onClear }: { onClear: () => void }) { return <div className="rounded-2xl border border-dashed border-black/20 bg-white p-14 text-center"><Search className="mx-auto h-8 w-8 text-black/25" /><h2 className="mt-4 font-display text-xl font-extrabold">No hostels match those filters</h2><p className="mt-2 text-sm text-black/50">Try widening your search or clearing a filter.</p><button onClick={onClear} className="mt-5 rounded-full bg-black px-5 py-3 text-xs font-bold text-white">Clear filters</button></div>; }
