import { Link } from "react-router-dom";
import { ArrowRight, BedDouble, CalendarDays, Check, ChevronDown, Heart, MapPin, Menu, Search, ShieldCheck, SlidersHorizontal, Sparkles, Star, Users, X } from "lucide-react";
import { useState } from "react";

const hostels = [
  { name: "Greenfield Residence", location: "Yaba, Lagos", university: "University of Lagos", price: "₦450,000", rating: "4.9", image: "https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=900&q=85", tag: "University verified", tone: "#e9c46a" },
  { name: "Campus View House", location: "Gwagwalada, Abuja", university: "University of Abuja", price: "₦380,000", rating: "4.8", image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=900&q=85", tag: "Popular this week", tone: "#9bc5c3" },
  { name: "The Study Grove", location: "Ile-Ife, Osun", university: "Obafemi Awolowo University", price: "₦290,000", rating: "4.7", image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=900&q=85", tag: "Move-in ready", tone: "#f4a261" },
];

const features = [
  { icon: ShieldCheck, title: "Verified places", text: "Every property is reviewed so you can book with confidence." },
  { icon: SlidersHorizontal, title: "Find your fit", text: "Compare rooms, amenities, price and distance in one view." },
  { icon: BedDouble, title: "Simple renting", text: "Apply, reserve and manage your accommodation from one place." },
  { icon: Sparkles, title: "Clear from day one", text: "Know exactly what you are paying for before you move in." },
];

export default function Index() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [university, setUniversity] = useState("");

  return <div className="min-h-screen bg-[#faf9f7] text-[#171717] selection:bg-[#f5b544] selection:text-black">
    <header className="sticky top-0 z-40 border-b border-white/10 bg-black text-white backdrop-blur-md">
      <div className="mx-auto flex h-[74px] max-w-[1240px] items-center justify-between px-5 lg:px-8">
        <Link to="/" className="font-display text-[25px] font-extrabold tracking-[-0.08em]">arc<span className="text-[#f5b544]">()</span></Link>
        <nav className="hidden items-center gap-7 text-[13px] font-medium text-white/75 lg:flex">
          <a href="#students" className="transition hover:text-[#a36500]">For students</a><a href="#owners" className="transition hover:text-[#a36500]">For hostel owners</a><a href="#how" className="transition hover:text-[#a36500]">How it works</a><Link to="/find-a-hostel" className="transition hover:text-[#a36500]">Find hostels</Link>
        </nav>
        <div className="hidden items-center gap-3 lg:flex"><Link to="/login" className="px-3 text-[13px] font-semibold">Log in</Link><Link to="/find-a-hostel" className="rounded-full border border-white/30 px-4 py-2 text-[13px] font-semibold transition hover:bg-white hover:text-black">Find a hostel</Link><Link to="/owner/dashboard" className="rounded-full bg-white px-4 py-2 text-[13px] font-semibold text-black transition hover:bg-[#f5b544]">List your hostel</Link></div>
        <button aria-label="Open navigation" className="lg:hidden" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button>
      </div>
      {menuOpen && <div className="border-t border-white/10 bg-black px-5 py-5 text-white lg:hidden"><div className="flex flex-col gap-4 text-sm font-semibold"><a href="#students" onClick={() => setMenuOpen(false)}>For students</a><a href="#owners" onClick={() => setMenuOpen(false)}>For hostel owners</a><Link to="/find-a-hostel">Find hostels</Link><button className="w-fit rounded-full bg-black px-5 py-2 text-white">List your hostel</button></div></div>}
    </header>

    <main>
      <section className="overflow-hidden border-b border-white/10 bg-black text-white">
        <div className="mx-auto grid max-w-[1240px] items-center gap-12 px-5 py-16 lg:grid-cols-[0.9fr_1.1fr] lg:px-8 lg:py-24">
          <div className="max-w-[560px]"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-xs font-semibold"><span className="h-2 w-2 rounded-full bg-[#25a65a]" /> Built for student life</div><h1 className="font-display text-[clamp(3.3rem,7vw,6.4rem)] font-extrabold leading-[.88] tracking-[-0.075em]">Find a place<br/>that feels <span className="text-[#e5a32d]">like home.</span></h1><p className="mt-7 max-w-[445px] text-[16px] leading-7 text-white/65">Discover trusted student hostels near your university. Compare rooms, prices, amenities and availability — all in one place.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/find-a-hostel" className="group rounded-full bg-[#f5b544] px-6 py-3.5 text-sm font-bold text-black transition hover:bg-white">Find a hostel <ArrowRight className="ml-2 inline h-4 w-4 transition group-hover:translate-x-1" /></Link><Link to="/owner/dashboard" className="rounded-full border border-white/30 bg-white/10 px-6 py-3.5 text-sm font-bold transition hover:bg-white hover:text-black">List your hostel</Link></div><p className="mt-4 text-xs font-medium text-white/45">Trusted accommodation for university students</p></div>
          <div className="relative min-h-[410px] lg:min-h-[500px]"><div className="absolute right-0 top-3 h-[78%] w-[74%] overflow-hidden rounded-[28px] border-[7px] border-white shadow-2xl shadow-black/10"><img src="https://images.unsplash.com/photo-1560185008-b033106af5c3?auto=format&fit=crop&w=1100&q=85" className="h-full w-full object-cover" alt="Bright student bedroom" /><div className="absolute bottom-4 left-4 rounded-2xl bg-white/95 p-3 shadow-lg"><p className="text-[10px] font-bold uppercase tracking-wider text-black/45">Available now</p><p className="mt-1 font-display text-lg font-extrabold">The Study Grove</p><p className="text-xs text-black/55">Ile-Ife · from ₦290k</p></div></div><div className="absolute bottom-2 left-0 z-10 w-[47%] overflow-hidden rounded-[24px] border-[7px] border-white bg-white shadow-xl"><img src="https://images.unsplash.com/photo-1517502884422-41eaead166d4?auto=format&fit=crop&w=700&q=85" className="h-44 w-full object-cover" alt="Students studying together" /><div className="flex items-center justify-between p-3"><div><p className="font-display text-sm font-bold">Made for focus</p><p className="text-[11px] text-black/50">Study spaces included</p></div><div className="rounded-full bg-[#f5b544] p-2"><Users className="h-4 w-4" /></div></div></div><div className="absolute right-[2%] top-[22%] z-10 flex items-center gap-2 rounded-full bg-black px-4 py-2.5 text-xs font-bold text-white shadow-lg"><MapPin className="h-4 w-4 text-[#f5b544]" /> 2.4km from campus</div></div>
        </div>
      </section>

      <section className="relative z-10 mx-auto -mt-8 max-w-[1060px] px-5"><div className="rounded-2xl border border-black/10 bg-white p-4 shadow-[0_18px_60px_rgba(0,0,0,.1)]"><div className="mb-3 flex items-center justify-between px-1"><div><p className="font-display text-lg font-extrabold">Start your search</p><p className="text-xs text-black/45">A better way to find your next room</p></div><Link to="/find-a-hostel" className="hidden text-xs font-bold text-[#a36500] sm:block">Advanced search <ArrowRight className="ml-1 inline h-3 w-3" /></Link></div><div className="grid gap-2 md:grid-cols-[1.25fr_1fr_1fr_1fr_auto]"><label className="search-field"><MapPin /><span><small>University</small><input placeholder="Where do you study?" value={university} onChange={e => setUniversity(e.target.value)} /></span></label><label className="search-field"><MapPin /><span><small>Location</small><input placeholder="City or area" /></span></label><label className="search-field"><CalendarDays /><span><small>Move-in date</small><input placeholder="Any date" /></span></label><label className="search-field"><BedDouble /><span><small>Room type</small><input placeholder="Any room" /></span></label><Link to="/find-a-hostel" className="flex items-center justify-center rounded-xl bg-[#f5b544] px-6 py-3 text-sm font-extrabold transition hover:bg-black hover:text-white"><Search className="mr-2 h-4 w-4" /> Search</Link></div></div></section>

      <section className="mx-auto max-w-[1240px] px-5 py-24 lg:px-8" id="students"><div className="grid gap-10 md:grid-cols-[.8fr_1.2fr] md:items-end"><div><p className="eyebrow">The arc() difference</p><h2 className="section-title mt-3">Everything you need<br/>to settle in.</h2></div><p className="max-w-[430px] text-sm leading-6 text-black/55">From your first search to the day you move in, arc() gives you a clearer, safer way to find student accommodation.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{features.map(({icon: Icon, title, text}, i) => <div key={title} className="feature-card"><div className={`mb-12 flex h-11 w-11 items-center justify-center rounded-xl ${i % 2 ? "bg-[#f7f0e4]" : "bg-[#f5b544]"}`}><Icon className="h-5 w-5" /></div><h3 className="font-display text-xl font-extrabold tracking-tight">{title}</h3><p className="mt-2 text-sm leading-6 text-black/55">{text}</p></div>)}</div></section>

      <section className="bg-[#151515] py-24 text-white"><div className="mx-auto max-w-[1240px] px-5 lg:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow text-[#f5b544]">Explore places to live</p><h2 className="section-title mt-3">Find your next<br/><span className="text-[#f5b544]">chapter.</span></h2></div><Link to="/find-a-hostel" className="w-fit rounded-full border border-white/30 px-5 py-3 text-sm font-bold transition hover:bg-white hover:text-black">Explore all hostels <ArrowRight className="ml-2 inline h-4 w-4" /></Link></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{hostels.map(h => <Link to="/hostels/greenfield-residence" key={h.name} className="group overflow-hidden rounded-2xl bg-[#242424] transition hover:-translate-y-1"><div className="relative h-64 overflow-hidden"><img src={h.image} alt={h.name} className="h-full w-full object-cover transition duration-500 group-hover:scale-105"/><span className="absolute left-4 top-4 rounded-full bg-white px-3 py-1.5 text-[11px] font-bold text-black"><ShieldCheck className="mr-1 inline h-3 w-3 text-[#1f9d55]" /> {h.tag}</span><button aria-label="Save hostel" className="absolute right-4 top-4 rounded-full bg-white/90 p-2 text-black" onClick={e => e.preventDefault()}><Heart className="h-4 w-4" /></button></div><div className="p-5"><div className="flex items-start justify-between"><div><h3 className="font-display text-xl font-bold">{h.name}</h3><p className="mt-1 text-xs text-white/55"><MapPin className="mr-1 inline h-3 w-3" />{h.location} · {h.university}</p></div><span className="flex items-center gap-1 text-sm font-bold"><Star className="h-4 w-4 fill-[#f5b544] text-[#f5b544]" />{h.rating}</span></div><div className="mt-5 flex items-end justify-between border-t border-white/10 pt-4"><p className="text-xs text-white/50">Starting from<br/><strong className="text-base text-white">{h.price}</strong> / session</p><span className="text-xs font-bold text-[#f5b544]">View rooms <ArrowRight className="ml-1 inline h-3 w-3" /></span></div></div></Link>)}</div></div></section>

      <section className="mx-auto grid max-w-[1240px] gap-14 px-5 py-24 lg:grid-cols-[.75fr_1.25fr] lg:px-8" id="how"><div><p className="eyebrow">Simple by design</p><h2 className="section-title mt-3">From search<br/>to move-in.</h2><p className="mt-5 max-w-[350px] text-sm leading-6 text-black/55">No endless tabs, confusing listings or surprise costs. Just a clear path to a place you’re happy to call home.</p></div><div className="space-y-0">{[["01", "Tell us what you need", "Choose your university, budget, preferred location and room type."],["02", "Explore your options", "Compare verified hostels, rooms, amenities, prices and availability."],["03", "Reserve your space", "Submit your application or reserve an available room."],["04", "Move in with confidence", "Complete payment and manage your stay through arc()."]].map(([num,title,text], i) => <div className="process-row" key={num}><span className="process-number">{num}</span><div><h3 className="font-display text-xl font-extrabold">{title}</h3><p className="mt-1 text-sm leading-6 text-black/55">{text}</p></div><ChevronDown className={`ml-auto h-5 w-5 text-black/25 ${i === 3 ? "hidden" : ""}`} /></div>)}</div></section>

      <section className="overflow-hidden bg-[#f5b544]" id="owners"><div className="mx-auto grid max-w-[1240px] items-center gap-10 px-5 py-20 lg:grid-cols-2 lg:px-8"><div><p className="eyebrow">For hostel owners</p><h2 className="section-title mt-3">Fill your hostel<br/>with the <span className="underline decoration-2 underline-offset-8">right</span> students.</h2><p className="mt-5 max-w-[450px] text-sm leading-6 text-black/65">List your property, manage available spaces and reach students looking for accommodation near their university.</p><div className="mt-8 flex flex-wrap gap-x-7 gap-y-3 text-sm font-bold">{["Create property listings","Manage rooms and beds","Track occupancy","Receive applications"].map(x => <span key={x}><Check className="mr-1 inline h-4 w-4" />{x}</span>)}</div><button className="mt-9 rounded-full bg-black px-6 py-3.5 text-sm font-bold text-white transition hover:bg-white hover:text-black">List your hostel <ArrowRight className="ml-2 inline h-4 w-4" /></button></div><div className="relative h-[300px] rounded-[28px] bg-[#151515] p-6 text-white shadow-2xl"><div className="flex items-center justify-between border-b border-white/15 pb-4"><span className="font-display font-bold">Property overview</span><span className="rounded-full bg-[#25a65a]/20 px-3 py-1 text-xs font-bold text-[#7ee6a5]">Live</span></div><div className="mt-7 grid grid-cols-3 gap-3">{[["245","Total beds"],["218","Occupied"],["27","Available"]].map(([n,l]) => <div className="rounded-xl bg-white/10 p-4" key={l}><strong className="font-display text-2xl">{n}</strong><p className="mt-1 text-[11px] text-white/55">{l}</p></div>)}</div><div className="mt-7"><div className="mb-2 flex justify-between text-xs"><span>Occupancy</span><strong>89%</strong></div><div className="h-2 rounded-full bg-white/15"><div className="h-full w-[89%] rounded-full bg-[#f5b544]" /></div></div></div></div></section>

      <section className="bg-[#151515] px-5 py-24 text-center text-white"><div className="mx-auto max-w-[740px]"><div className="font-display text-2xl font-extrabold tracking-[-.08em]">arc<span className="text-[#f5b544]">()</span></div><h2 className="font-display mt-7 text-[clamp(2.5rem,6vw,5rem)] font-extrabold leading-[.92] tracking-[-.07em]">Your next room is<br/><span className="text-[#f5b544]">closer than you think.</span></h2><p className="mx-auto mt-5 text-sm text-white/55">Search. Compare. Reserve. Move in.</p><div className="mt-8 flex justify-center gap-3"><Link to="/find-a-hostel" className="rounded-full bg-[#f5b544] px-6 py-3.5 text-sm font-bold text-black transition hover:bg-white">Find a hostel</Link><button className="rounded-full border border-white/30 px-6 py-3.5 text-sm font-bold transition hover:bg-white hover:text-black">List your hostel</button></div></div></section>
    </main>
    <footer className="bg-[#151515] px-5 pb-8 text-white lg:px-8"><div className="mx-auto max-w-[1240px] border-t border-white/15 pt-10"><div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-[1.3fr_1fr_1fr_1fr]"><div><div className="font-display text-2xl font-extrabold tracking-[-.08em]">arc<span className="text-[#f5b544]">()</span></div><p className="mt-4 max-w-[220px] text-sm leading-6 text-white/45">Helping students find better places to live.</p></div>{[["FOR STUDENTS","Find hostels","Saved hostels","My bookings","Help center"],["FOR HOSTEL OWNERS","List your hostel","Manage properties","Manage bookings","Pricing"],["COMPANY","About","How it works","Contact","Safety"]].map(([title,...links]) => <div key={title}><p className="text-[11px] font-bold tracking-widest text-white/35">{title}</p><div className="mt-4 space-y-3 text-sm text-white/65">{links.map(l => <p key={l}>{l}</p>)}</div></div>)}</div><div className="mt-12 flex flex-col justify-between gap-3 border-t border-white/15 pt-5 text-xs text-white/35 sm:flex-row"><span>© 2026 arc()</span><span>Privacy · Terms · Safety</span></div></div></footer>
  </div>;
}
