import { ArrowRight, Bell, CalendarDays, Check, CreditCard, Heart, Home, LogOut, Mail, MessageCircle, Search, Settings, ShieldCheck, UserRound, Wallet } from "lucide-react";
import { Link, useLocation } from "react-router-dom";

const nav = [["/student", Home, "Overview"], ["/student/search", Search, "Discover"], ["/student/saved", Heart, "Saved hostels"], ["/student/applications", ShieldCheck, "Applications"], ["/student/bookings", CalendarDays, "My bookings"], ["/student/payments", Wallet, "Payments"], ["/student/messages", MessageCircle, "Messages"], ["/student/profile", UserRound, "Profile"]] as const;
const saved = [{ name: "Campus View House", location: "Gwagwalada, Abuja", price: "₦380,000", image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=500&q=80" }, { name: "The Study Grove", location: "Ile-Ife, Osun", price: "₦290,000", image: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&w=500&q=80" }];
const titleMap: Record<string, [string, string]> = { "/student/saved": ["Saved hostels", "Keep your shortlist close while you decide."], "/student/applications": ["Applications", "Track every request from submitted to approved."], "/student/bookings": ["My bookings", "Your current and upcoming accommodation."], "/student/payments": ["Payments", "Review accommodation charges and payment history."], "/student/messages": ["Messages", "Stay connected with hostel management."], "/student/profile": ["Profile & preferences", "Keep your details and search preferences up to date."] };

export default function StudentPortal() {
  const path = useLocation().pathname;
  const [title, subtitle] = titleMap[path] ?? ["Good morning, Alex.", "Find your next home, or manage the one you have."];
  return <div className="min-h-screen bg-[#f7f6f3] text-[#171717]"><header className="border-b border-white/10 bg-black text-white"><div className="mx-auto flex h-[74px] max-w-[1240px] items-center justify-between px-5 lg:px-8"><Link to="/" className="font-display text-[25px] font-extrabold tracking-[-.08em]">arc<span className="text-[#f5b544]">()</span></Link><div className="flex items-center gap-4"><Bell className="h-5 w-5" /><div className="flex items-center gap-2 border-l border-white/20 pl-4"><span className="flex h-8 w-8 items-center justify-center rounded-full bg-[#f5b544] text-xs font-bold text-black">AK</span><span className="hidden text-sm font-semibold sm:block">Alex K.</span></div></div></div></header><div className="mx-auto grid max-w-[1240px] gap-8 px-5 py-8 lg:grid-cols-[210px_1fr] lg:px-8"><aside className="hidden lg:block"><p className="eyebrow">Student space</p><h2 className="mt-2 font-display text-xl font-extrabold">My arc()</h2><nav className="mt-8 space-y-1">{nav.map(([href, Icon, label]) => <Link key={href} to={href} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold ${path === href ? "bg-black text-white" : "text-black/55 hover:bg-white hover:text-black"}`}><Icon className="h-4 w-4" />{label}</Link>)}</nav><Link to="/" className="mt-20 flex items-center gap-3 px-3 text-xs font-bold text-black/40"><LogOut className="h-4 w-4" /> Log out</Link></aside><main><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="eyebrow">Student dashboard</p><h1 className="mt-2 font-display text-4xl font-extrabold tracking-[-.06em]">{title}</h1><p className="mt-2 text-sm text-black/50">{subtitle}</p></div><Link to="/find-a-hostel" className="w-fit rounded-full bg-black px-5 py-3 text-sm font-bold text-white">Search accommodation <ArrowRight className="ml-2 inline h-4 w-4" /></Link></div>{path === "/student" ? <Overview /> : path === "/student/saved" ? <Saved /> : path === "/student/applications" ? <Applications /> : path === "/student/bookings" ? <Bookings /> : path === "/student/payments" ? <Payments /> : path === "/student/messages" ? <Messages /> : <Profile />}</main></div></div>;
}
function Overview() { return <><section className="rounded-2xl bg-black p-6 text-white sm:p-8"><div className="flex flex-col justify-between gap-7 md:flex-row md:items-end"><div><p className="text-xs font-bold uppercase tracking-widest text-[#f5b544]">Your accommodation</p><h2 className="mt-3 font-display text-3xl font-extrabold">Greenfield Residence</h2><p className="mt-2 text-sm text-white/55">Yaba, Lagos · Room A203 · Bed 2</p></div><div><p className="text-xs text-white/45">Move-in date</p><p className="mt-1 font-display text-2xl font-extrabold">September 18</p></div></div><div className="mt-7 flex gap-3"><button className="rounded-full bg-[#f5b544] px-5 py-3 text-xs font-bold text-black">View booking</button><button className="rounded-full border border-white/25 px-5 py-3 text-xs font-bold">Contact hostel</button></div></section><div className="mt-10"><Saved /></div></> }
function Saved() { return <section><div className="grid gap-4 sm:grid-cols-2">{saved.map(item => <Link to="/hostels/greenfield-residence" key={item.name} className="flex gap-4 rounded-2xl border border-black/10 bg-white p-3 transition hover:shadow-lg"><img src={item.image} className="h-28 w-28 rounded-xl object-cover" alt=""/><div className="py-1"><div className="flex justify-between gap-5"><h3 className="font-display font-extrabold">{item.name}</h3><Heart className="h-4 w-4 fill-[#f5b544] text-[#f5b544]" /></div><p className="mt-2 text-xs text-black/45">{item.location}</p><p className="mt-5 text-sm font-extrabold">{item.price} <span className="text-[10px] font-medium text-black/45">/ session</span></p></div></Link>)}</div></section> }
function Applications() { return <div className="space-y-4"><div className="rounded-2xl border border-black/10 bg-white p-6"><div className="flex justify-between"><div><h2 className="font-display text-xl font-extrabold">Greenfield Residence</h2><p className="mt-1 text-xs text-black/45">Single room · Submitted Sept 4</p></div><span className="rounded-full bg-[#fff4d6] px-3 py-1 text-xs font-bold text-[#996b00]">Under review</span></div><div className="mt-7 flex items-center gap-2">{["Submitted", "Under review", "Decision"].map((step, i) => <div className="flex flex-1 items-center gap-2" key={step}><span className={`h-3 w-3 rounded-full ${i < 2 ? "bg-[#f5b544]" : "border border-black/20"}`} /><span className="text-[11px] font-semibold text-black/55">{step}</span>{i < 2 && <span className="h-px flex-1 bg-black/15" />}</div>)}</div></div></div> }
function Bookings() { return <div className="grid gap-4"><div className="rounded-2xl bg-black p-6 text-white"><p className="eyebrow text-[#f5b544]">Upcoming</p><h2 className="mt-2 font-display text-2xl font-extrabold">Greenfield Residence</h2><p className="mt-2 text-sm text-white/55">Room A203 · Bed 2 · Move-in September 18</p><button className="mt-6 rounded-full bg-[#f5b544] px-5 py-3 text-xs font-bold text-black">View booking</button></div><div className="rounded-2xl border border-black/10 bg-white p-6"><p className="eyebrow">Previous</p><p className="mt-2 text-sm font-bold">No previous bookings yet.</p></div></div> }
function Payments() { return <div className="rounded-2xl border border-black/10 bg-white p-6"><div className="flex items-center gap-3"><CreditCard className="h-5 w-5 text-[#a36500]" /><h2 className="font-display text-xl font-extrabold">Payment history</h2></div><div className="mt-6 divide-y divide-black/10"><div className="flex justify-between py-4 text-sm"><span>Greenfield Residence · Deposit</span><strong>₦110,000</strong></div><div className="flex justify-between py-4 text-xs text-black/45"><span>Payment due September 10</span><span>Pending</span></div></div></div> }
function Messages() { return <div className="grid gap-3"><div className="rounded-2xl border border-black/10 bg-white p-5"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-full bg-[#f5b544]"><Mail className="h-4 w-4" /></span><div><h2 className="font-display font-extrabold">Greenfield Residence</h2><p className="mt-1 text-xs text-black/50">Your room is ready for inspection...</p></div><span className="ml-auto text-xs text-black/40">Today</span></div></div></div> }
function Profile() { return <div className="max-w-xl rounded-2xl border border-black/10 bg-white p-6"><h2 className="font-display text-xl font-extrabold">Personal details</h2><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold">First name<input className="auth-input" defaultValue="Alex" /></label><label className="text-xs font-bold">Last name<input className="auth-input" defaultValue="Kalu" /></label><label className="text-xs font-bold sm:col-span-2">Email<input className="auth-input" defaultValue="alex@example.com" /></label></div><button className="mt-6 rounded-full bg-black px-5 py-3 text-xs font-bold text-white">Save changes</button></div> }
