import { ReactNode, useEffect, useState } from "react";
import { Link, useLocation } from "react-router-dom";
import {
  ArrowRight,
  BarChart3,
  Bell,
  Building2,
  CalendarDays,
  Check,
  CheckCircle2,
  ClipboardCheck,
  CreditCard,
  DollarSign,
  FileWarning,
  LayoutDashboard,
  LogOut,
  Search,
  Settings,
  ShieldAlert,
  Users,
  X,
} from "lucide-react";

type PropertyStatus = "under_review" | "verified" | "changes_requested";
type PropertyRecord = { property?: { name?: string; description?: string; city?: string; area?: string; university?: string; distance?: string }; photos?: string[]; amenities?: string[]; rooms?: { name: string; beds: number; price: string }[]; submittedAt?: string; status?: PropertyStatus };
type ApplicationRecord = { id: string; firstName: string; lastName: string; university: string; status?: string };

const nav = [["/admin", LayoutDashboard, "Overview"], ["/admin/users", Users, "Users"], ["/admin/properties", Building2, "Properties"], ["/admin/verification", ClipboardCheck, "Verification"], ["/admin/bookings", CalendarDays, "Bookings"], ["/admin/payments", DollarSign, "Payments"], ["/admin/disputes", FileWarning, "Disputes"], ["/admin/reports", BarChart3, "Reports"], ["/admin/settings", Settings, "Settings"]] as const;
const titles: Record<string, [string, string]> = { "/admin": ["Overview", "Monitor the arc() marketplace."], "/admin/users": ["Users", "Manage students, owners, and university partners."], "/admin/properties": ["Properties", "Review the accommodation marketplace inventory."], "/admin/verification": ["Verification", "Keep property and partner verification moving."], "/admin/bookings": ["Bookings", "Monitor reservations and move-in activity."], "/admin/payments": ["Payments", "Review marketplace payment activity."], "/admin/disputes": ["Disputes", "Resolve issues with care and a clear record."], "/admin/reports": ["Reports", "Understand platform activity and outcomes."], "/admin/settings": ["Settings", "Manage platform preferences and controls."] };

function readProperty(): PropertyRecord | null { try { const saved = window.localStorage.getItem("arc-owner-property"); return saved ? (JSON.parse(saved) as PropertyRecord) : null; } catch { return null; } }
function readApplication(): ApplicationRecord | null { try { const saved = window.localStorage.getItem("arc.student.application"); return saved ? (JSON.parse(saved) as ApplicationRecord) : null; } catch { return null; } }

function Shell({ children }: { children: ReactNode }) { const path = useLocation().pathname; return <div className="min-h-screen bg-[#f7f6f3] text-[#171717]"><header className="border-b border-white/10 bg-black text-white"><div className="mx-auto flex h-[74px] max-w-[1240px] items-center justify-between px-5 lg:px-8"><Link to="/" className="font-display text-[25px] font-extrabold tracking-[-.08em]">arc<span className="text-[#f5b544]">()</span></Link><span className="hidden text-sm font-semibold text-white/70 sm:block">Admin workspace</span><Link to="/" className="text-xs font-bold text-white/60"><LogOut className="mr-2 inline h-4 w-4" /> Exit</Link></div></header><div className="mx-auto grid max-w-[1240px] gap-8 px-5 py-8 lg:grid-cols-[230px_1fr] lg:px-8"><aside className="hidden lg:block"><p className="eyebrow">Platform control</p><h2 className="mt-2 font-display text-xl font-extrabold">Admin console</h2><nav className="mt-8 space-y-1">{nav.map(([href, Icon, label]) => <Link key={href} to={href} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-semibold ${path === href ? "bg-black text-white" : "text-black/55 hover:bg-white"}`}><Icon className="h-4 w-4" />{label}</Link>)}</nav></aside><main>{children}</main></div></div>; }
function Heading({ path }: { path: string }) { const [title, subtitle] = titles[path] ?? ["Admin workspace", "Manage the arc() marketplace."]; return <div><p className="eyebrow">Platform control</p><h1 className="mt-2 font-display text-4xl font-extrabold tracking-[-.06em] sm:text-5xl">{title}</h1><p className="mt-3 text-sm text-black/50">{subtitle}</p></div>; }
function Empty({ icon: Icon, title, copy, action = "Return to overview", href = "/admin" }: { icon: typeof Building2; title: string; copy: string; action?: string; href?: string }) { return <section className="mt-8 rounded-2xl border border-dashed border-black/20 bg-white p-10 text-center sm:p-14"><div className="mx-auto flex h-14 w-14 items-center justify-center rounded-full bg-[#fff4d6] text-[#a36500]"><Icon /></div><h2 className="mt-5 font-display text-2xl font-extrabold">{title}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-black/50">{copy}</p><Link to={href} className="mt-6 inline-flex rounded-full bg-black px-5 py-3 text-xs font-bold text-white">{action}<ArrowRight className="ml-2 h-4 w-4" /></Link></section>; }
function Status({ status }: { status: PropertyStatus }) { const label = status === "verified" ? "Verified" : status === "changes_requested" ? "Changes requested" : "Under review"; const style = status === "verified" ? "bg-[#dff3e6] text-[#16733b]" : status === "changes_requested" ? "bg-[#ffe3e3] text-[#a52a2a]" : "bg-[#fff4d6] text-[#8a5d00]"; return <span className={`rounded-full px-3 py-2 text-[11px] font-bold ${style}`}>{label}</span>; }
function PropertyCard({ property, action }: { property: PropertyRecord; action?: ReactNode }) { const details = property.property ?? {}; return <section className="mt-8 rounded-2xl border border-black/10 bg-white p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><p className="text-xs font-bold text-black/45">Property record</p><h2 className="mt-2 font-display text-2xl font-extrabold">{details.name || "Unnamed property"}</h2><p className="mt-1 text-sm text-black/50">{details.city || "City not set"}{details.area ? ` · ${details.area}` : ""} {details.university ? `· Near ${details.university}` : ""}</p></div>{property.status && <Status status={property.status} />}</div><div className="mt-7 grid gap-5 border-t border-black/10 pt-6 sm:grid-cols-4"><div><p className="text-xs text-black/45">Photos</p><p className="mt-1 text-lg font-bold">{property.photos?.length ?? 0}</p></div><div><p className="text-xs text-black/45">Amenities</p><p className="mt-1 text-lg font-bold">{property.amenities?.length ?? 0}</p></div><div><p className="text-xs text-black/45">Room types</p><p className="mt-1 text-lg font-bold">{property.rooms?.length ?? 0}</p></div><div><p className="text-xs text-black/45">Beds</p><p className="mt-1 text-lg font-bold">{property.rooms?.reduce((sum, room) => sum + room.beds, 0) ?? 0}</p></div></div>{action && <div className="mt-6">{action}</div>}</section>; }
function Overview({ property, application }: { property: PropertyRecord | null; application: ApplicationRecord | null }) { return <><div className="mt-8 grid gap-4 sm:grid-cols-4"><div className="rounded-2xl border border-black/10 bg-white p-5"><Users className="h-5 w-5 text-[#a36500]" /><p className="mt-6 font-display text-3xl font-extrabold">{application ? "1" : "—"}</p><p className="mt-1 text-xs text-black/50">User records</p></div><div className="rounded-2xl border border-black/10 bg-white p-5"><Building2 className="h-5 w-5 text-[#a36500]" /><p className="mt-6 font-display text-3xl font-extrabold">{property ? "1" : "—"}</p><p className="mt-1 text-xs text-black/50">Properties</p></div><div className="rounded-2xl border border-black/10 bg-white p-5"><ClipboardCheck className="h-5 w-5 text-[#a36500]" /><p className="mt-6 font-display text-3xl font-extrabold">{property?.status === "under_review" ? "1" : "—"}</p><p className="mt-1 text-xs text-black/50">Review queue</p></div><div className="rounded-2xl border border-black/10 bg-white p-5"><ShieldAlert className="h-5 w-5 text-[#a36500]" /><p className="mt-6 font-display text-3xl font-extrabold">—</p><p className="mt-1 text-xs text-black/50">Open disputes</p></div></div>{property ? <PropertyCard property={property} action={<Link to="/admin/verification" className="inline-flex rounded-full bg-black px-5 py-3 text-xs font-bold text-white">Open verification <ArrowRight className="ml-2 h-4 w-4" /></Link>} /> : <Empty icon={LayoutDashboard} title="Admin workspace is ready" copy="Marketplace records, verification queues, and reports will appear here when live platform data is connected." action="Review verification" href="/admin/verification" />}</>; }
function Verification({ property, setProperty }: { property: PropertyRecord | null; setProperty: (property: PropertyRecord) => void }) { const [confirming, setConfirming] = useState<PropertyStatus | null>(null); const [notice, setNotice] = useState(""); if (!property) return <Empty icon={ClipboardCheck} title="Verification queue is empty" copy="No property records are waiting for platform review." action="View properties" href="/admin/properties" />; const update = (status: PropertyStatus) => { const next = { ...property, status }; window.localStorage.setItem("arc-owner-property", JSON.stringify(next)); setProperty(next); setConfirming(null); setNotice(status === "verified" ? "Property approved for the marketplace." : "Changes requested from the owner."); }; return <><PropertyCard property={property} />{notice && <div className="mt-4 flex items-center gap-2 rounded-xl bg-[#dff3e6] px-4 py-3 text-xs font-bold text-[#16733b]" role="status"><CheckCircle2 className="h-4 w-4" />{notice}</div>}<div className="mt-5 flex flex-wrap gap-3"><button onClick={() => setConfirming("changes_requested")} className="rounded-full border border-[#a52a2a]/20 px-4 py-3 text-xs font-bold text-[#a52a2a]">Request changes</button><button onClick={() => setConfirming("verified")} className="rounded-full bg-black px-4 py-3 text-xs font-bold text-white">Approve property <Check className="ml-2 inline h-4 w-4" /></button></div>{confirming && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><div className="w-full max-w-[420px] rounded-2xl bg-white p-7"><button onClick={() => setConfirming(null)} className="float-right rounded-full p-1 text-black/45"><X className="h-5 w-5" /></button><p className="eyebrow">Confirm admin action</p><h2 className="mt-2 font-display text-2xl font-extrabold">{confirming === "verified" ? "Approve property?" : "Request changes?"}</h2><p className="mt-2 text-sm leading-6 text-black/55">This updates the local preview status. Backend moderation will replace this state later.</p><div className="mt-6 flex gap-3"><button onClick={() => setConfirming(null)} className="flex-1 rounded-full border border-black/15 py-3 text-xs font-bold">Cancel</button><button onClick={() => update(confirming)} className="flex-1 rounded-full bg-black py-3 text-xs font-bold text-white">Confirm</button></div></div></div>}</>; }
function Properties({ property }: { property: PropertyRecord | null }) { return property ? <><div className="mt-8 flex items-center gap-3 rounded-2xl border border-black/10 bg-white p-4"><Search className="h-4 w-4 text-black/35" /><input className="w-full bg-transparent text-sm outline-none" placeholder="Search properties when live data is connected" /></div><PropertyCard property={property} action={<Link to="/admin/verification" className="inline-flex rounded-full border border-black/15 px-4 py-3 text-xs font-bold">Review record <ArrowRight className="ml-2 h-4 w-4" /></Link>} /></> : <Empty icon={Building2} title="No properties yet" copy="Property records submitted to the marketplace will appear here for moderation." action="Open verification" href="/admin/verification" />; }
function UsersPage({ application }: { application: ApplicationRecord | null }) { return application ? <section className="mt-8 rounded-2xl border border-black/10 bg-white p-6"><p className="text-xs font-bold text-black/45">Current preview user record</p><h2 className="mt-2 font-display text-2xl font-extrabold">{application.firstName} {application.lastName}</h2><p className="mt-1 text-sm text-black/50">Student · {application.university}</p><p className="mt-6 text-xs leading-5 text-black/50">User roles, account status, authentication history, and moderation actions will be supplied by the backend.</p></section> : <Empty icon={Users} title="No user records yet" copy="Students, owners, and university partners will appear here when accounts are connected." action="Return to overview" />; }
function Generic({ title, icon: Icon }: { title: string; icon: typeof Building2 }) { return <Empty icon={Icon} title={`${title} workspace ready`} copy="This frontend surface is ready for live platform data, filters, actions, and API integration." />; }

export default function AdminPortal() { const path = useLocation().pathname; const [property, setProperty] = useState<PropertyRecord | null>(null); const [application, setApplication] = useState<ApplicationRecord | null>(null); const [loading, setLoading] = useState(true); useEffect(() => { setProperty(readProperty()); setApplication(readApplication()); setLoading(false); }, []); if (loading) return <Shell><div className="h-64 animate-pulse rounded-2xl bg-black/5" /></Shell>; return <Shell><Heading path={path} />{path === "/admin" ? <Overview property={property} application={application} /> : path === "/admin/properties" ? <Properties property={property} /> : path === "/admin/verification" ? <Verification property={property} setProperty={setProperty} /> : path === "/admin/users" ? <UsersPage application={application} /> : path === "/admin/disputes" ? <Generic title="Disputes" icon={FileWarning} /> : path === "/admin/bookings" ? <Generic title="Bookings" icon={CalendarDays} /> : path === "/admin/payments" ? <Generic title="Payments" icon={CreditCard} /> : path === "/admin/reports" ? <Generic title="Reports" icon={BarChart3} /> : <Generic title={titles[path]?.[0] ?? "Admin"} icon={Settings} />}</Shell>; }
